project:
  type: website
  output-dir: _site

website:
  title: "rsonar Presentation"
  navbar:
    left:
      - href: index.qmd
        text: Français
      - href: index_en.qmd
        text: English

format:
  revealjs:
    theme: [default]
    slide-number: true
    controls: true
    progress: true
    toc: false
    transition: fade
    center: false

execute:
  echo: true
  warning: false
  message: false
